aws_access_key              = "your_aws_access_key_id"
aws_secret_key              = "your_aws_secret_key"
ssh_keypair_name            = "your_ssh_key_pem"
ssh_private_key_file_path   = "/path/of/your_ssh_key_pem"
gmail_oauth_client_id       = "your_google_client_id"
gmail_oauth_client_secret   = "your_google_client_secret"
